import { Report } from '../types';

export const MOCK_REPORTS: Report[] = [
  {
    id: '1',
    title: 'Q4 2024 Financial Performance Overview',
    category: 'Finance',
    status: 'published',
    author: 'Sarah Chen',
    createdAt: '2024-12-15T09:00:00Z',
    updatedAt: '2024-12-20T14:30:00Z',
    summary: 'Comprehensive analysis of Q4 financial results showing 23% YoY revenue growth.',
    content: `This report provides a detailed analysis of the company's financial performance in Q4 2024. Revenue grew by 23% year-over-year, reaching $45.2M, driven primarily by expansion in the enterprise segment. Operating expenses were well-controlled at 67% of revenue. EBITDA margin expanded to 18.5%, up from 15.2% in Q4 2023. Key highlights include successful launches in APAC markets, strong renewal rates at 94%, and reduction in customer acquisition cost by 12%. The balance sheet remains healthy with $28M in cash and equivalents. Looking ahead to Q1 2025, pipeline visibility is strong with $62M in qualified opportunities.`,
    tags: ['finance', 'quarterly', 'revenue', 'growth'],
    metrics: { views: 1423, downloads: 287 },
  },
  {
    id: '2',
    title: 'Supply Chain Optimization Initiative — 2024 Results',
    category: 'Operations',
    status: 'published',
    author: 'Marcus Williams',
    createdAt: '2024-11-10T08:00:00Z',
    updatedAt: '2024-11-28T11:00:00Z',
    summary: 'Results from the 18-month supply chain overhaul reducing lead times by 34%.',
    content: `Following an 18-month initiative to modernize our supply chain infrastructure, this report documents the measurable outcomes achieved in 2024. Lead times decreased by 34% across all product lines, from an average of 21 days to 13.8 days. Inventory holding costs were reduced by $3.1M annually through implementation of just-in-time principles and predictive demand forecasting. Supplier on-time delivery rates improved from 78% to 94% through new SLA frameworks and supplier scorecarding. The automation of 6 distribution centers is now complete, reducing per-unit handling costs by 19%. Customer satisfaction scores related to delivery improved from 3.6 to 4.4 out of 5. Projected savings over 3 years are estimated at $14.7M.`,
    tags: ['operations', 'supply-chain', 'efficiency', 'automation'],
    metrics: { views: 892, downloads: 143 },
  },
  {
    id: '3',
    title: 'Brand Awareness Campaign: Summer 2024 Post-Mortem',
    category: 'Marketing',
    status: 'published',
    author: 'Priya Nair',
    createdAt: '2024-09-05T10:00:00Z',
    updatedAt: '2024-09-18T16:00:00Z',
    summary: 'Deep-dive into summer campaign performance across channels with ROI analysis.',
    content: `The Summer 2024 brand awareness campaign ran from June 1 to August 31 across digital, OOH, and partnership channels with a total budget of $2.4M. Overall brand recall lifted by 14% in target demographics (25–44, urban professionals). Digital channels delivered a combined ROAS of 3.2x. Paid social outperformed benchmarks with CTR of 2.8% vs industry average of 1.1%. The OOH activation in 5 major cities drove a measurable 8% lift in direct traffic. Influencer partnerships reached 12M unique users with an average engagement rate of 4.7%. Areas for improvement include email nurture sequencing (open rates lagged at 21%) and YouTube pre-roll performance. Recommendations for Q4 include reallocating 15% of OOH budget to connected TV.`,
    tags: ['marketing', 'brand', 'campaign', 'ROI'],
    metrics: { views: 2145, downloads: 421 },
  },
  {
    id: '4',
    title: 'Engineering Team Velocity Report — H2 2024',
    category: 'Technical',
    status: 'published',
    author: 'Alex Romero',
    createdAt: '2024-12-01T08:00:00Z',
    updatedAt: '2024-12-10T12:00:00Z',
    summary: 'Engineering throughput, quality metrics, and platform reliability for H2 2024.',
    content: `This report covers engineering velocity, code quality, and infrastructure reliability across H2 2024. Sprint velocity averaged 78 story points per sprint across all product teams, up 12% from H1. Deployment frequency increased to 4.2 deploys per day from 2.8 in H1 2024. Mean time to recovery (MTTR) improved dramatically from 47 minutes to 12 minutes following adoption of improved observability tooling. System uptime held at 99.94% despite a 3x increase in API traffic. Bug escape rate to production fell from 8.2% to 3.1% following rollout of automated integration tests. Technical debt reduction initiatives closed 142 long-standing issues. The migration of core services to Kubernetes is 80% complete and on track for Q1 2025 completion.`,
    tags: ['engineering', 'velocity', 'infrastructure', 'reliability'],
    metrics: { views: 673, downloads: 98 },
  },
  {
    id: '5',
    title: 'Employee Engagement & Retention Study 2024',
    category: 'HR',
    status: 'published',
    author: 'Jordan Lee',
    createdAt: '2024-10-20T09:00:00Z',
    updatedAt: '2024-10-30T17:00:00Z',
    summary: 'Annual engagement survey results with retention risk analysis and action plans.',
    content: `The 2024 Annual Employee Engagement Survey achieved an 87% participation rate across all departments. Overall engagement score improved to 74/100 from 68/100 in 2023, surpassing the industry benchmark of 71. Key drivers of engagement were leadership transparency (+11 pts), growth opportunities (+9 pts), and flexible work arrangements (+14 pts). Areas requiring attention include cross-team collaboration (61/100) and compensation competitiveness (58/100). Voluntary attrition rate for 2024 was 11.2%, down from 15.8% in 2023. High-performer retention improved to 94% following implementation of accelerated career tracks. Predictive churn modeling identified 23 at-risk employees; targeted interventions have been initiated. Hiring velocity increased with average time-to-fill reduced from 47 to 31 days.`,
    tags: ['HR', 'engagement', 'retention', 'culture'],
    metrics: { views: 1102, downloads: 189 },
  },
  {
    id: '6',
    title: 'Market Expansion Analysis: Southeast Asia Entry Strategy',
    category: 'Marketing',
    status: 'draft',
    author: 'Linda Zhao',
    createdAt: '2024-12-08T11:00:00Z',
    updatedAt: '2024-12-19T15:00:00Z',
    summary: 'Feasibility and go-to-market strategy for SEA market entry in 2025.',
    content: `This draft report evaluates the strategic opportunity for market entry into Southeast Asia, with primary focus on Singapore, Indonesia, and Vietnam. Total addressable market across these three markets is estimated at $780M by 2027. Competitive landscape analysis reveals 4 established players but significant whitespace in the mid-market segment. Recommended entry sequence: Singapore (Q2 2025, regulatory-friendly), Vietnam (Q4 2025, growth-led), Indonesia (Q2 2026, partnership-led). Required investment over 24 months estimated at $5.8M, with projected break-even at month 29. Key risks include regulatory complexity in Indonesia, currency volatility, and local talent acquisition. Strategic partnerships with two regional SIs have been identified as critical enablers. Additional research required on Vietnam data residency requirements before finalizing strategy.`,
    tags: ['marketing', 'strategy', 'expansion', 'APAC'],
    metrics: { views: 234, downloads: 12 },
  },
  {
    id: '7',
    title: 'Infrastructure Cost Optimization — AWS Audit 2024',
    category: 'Technical',
    status: 'published',
    author: 'Devon Park',
    createdAt: '2024-11-22T08:00:00Z',
    updatedAt: '2024-12-02T10:00:00Z',
    summary: 'AWS cost audit identifying $890K in annual savings through rightsizing and reservations.',
    content: `A comprehensive audit of our AWS infrastructure conducted across November 2024 identified $890K in annualized savings opportunities. Analysis covered 340 EC2 instances, 48 RDS databases, and 12TB of S3 storage. Immediate actions (savings: $290K/yr): Rightsizing 67 over-provisioned EC2 instances, deleting 23 unused Elastic IPs, removing 4TB of orphaned EBS volumes. Short-term actions (savings: $380K/yr): Purchasing 3-year reserved instances for baseline workloads, migrating eligible databases to Aurora Serverless. Medium-term actions (savings: $220K/yr): Implementing S3 intelligent tiering, adopting Graviton3 instances for compute-intensive workloads. Implementation roadmap spans 6 months with a total migration effort estimated at 340 engineering hours. Quick wins have already been executed with $78K in realized savings since audit completion.`,
    tags: ['technical', 'cloud', 'cost', 'infrastructure'],
    metrics: { views: 521, downloads: 77 },
  },
  {
    id: '8',
    title: 'Annual Compliance & Risk Assessment Report 2024',
    category: 'Operations',
    status: 'archived',
    author: 'Fiona O\'Brien',
    createdAt: '2024-01-15T09:00:00Z',
    updatedAt: '2024-02-01T16:00:00Z',
    summary: 'Comprehensive risk and compliance landscape with mitigation status for FY2024.',
    content: `This annual compliance and risk assessment covers the regulatory, operational, and strategic risk landscape for fiscal year 2024. Regulatory compliance: GDPR audit completed with zero major findings; SOC 2 Type II certification renewed in March 2024; PCI DSS Level 1 compliance maintained. Risk register was updated to include 18 new risks, of which 14 have been assigned mitigations and 4 are under evaluation. Top strategic risks for the year included macroeconomic headwinds (likelihood: high, impact: high), key supplier concentration (likelihood: medium, impact: high), and cybersecurity threats (likelihood: high, impact: high). The cybersecurity posture was significantly strengthened through rollout of MFA across all systems, a zero-trust network architecture project (60% complete), and two successful penetration testing exercises. Insurance coverage was reviewed and updated in Q3 to ensure alignment with current risk profile.`,
    tags: ['compliance', 'risk', 'operations', 'legal'],
    metrics: { views: 389, downloads: 203 },
  },
];
